### ISSUE TITLE
Failed to start bean 'blPersistenceService'

### ISSUE THREAD

**Issue by DamianSheldon** [BroadleafCommerce/CommunityStarter#34]
Follow [Extending Customer For Heat Clinic Tutorial](https://www.broadleafcommerce.com/docs/core/current/tutorials/getting-started-tutorials/extending-customer-for-heat-clinic-tutorial),

```
2018-06-08 16:16:31.740 ERROR 30358 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'blPersistenceService'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at com.community.SiteApplication.main(SiteApplication.java:22) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.13.RELEASE.jar:1.5.13.RELEASE]
Caused by: java.lang.NullPointerException: null
	at org.broadleafcommerce.common.service.PersistenceServiceImpl.getManagedClassName(PersistenceServiceImpl.java:270) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.service.PersistenceServiceImpl.buildManagerCacheKey(PersistenceServiceImpl.java:257) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.service.PersistenceServiceImpl.buildManagerCacheKey(PersistenceServiceImpl.java:253) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.service.PersistenceServiceImpl.populateCaches(PersistenceServiceImpl.java:139) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.service.PersistenceServiceImpl$1.execute(PersistenceServiceImpl.java:122) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runOptionalTransactionalOperation(StreamingTransactionCapableUtil.java:174) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.util.StreamingTransactionCapableUtil.runTransactionalOperation(StreamingTransactionCapableUtil.java:115) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.service.PersistenceServiceImpl.initializeEntityManagerCache(PersistenceServiceImpl.java:119) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.broadleafcommerce.common.service.PersistenceServiceImpl.start(PersistenceServiceImpl.java:96) ~[broadleaf-common-5.2.4-GA.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	... 17 common frames omitted
```

**Comment by DamianSheldon** [comment]
Today I figured it out, it caused by spring-boot-devtools. I add this dependency for replacing Jrebel, it unfortunately bring such a strange bug.
